[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-src https://itch.io https://*.itch.io https://*.itch.zone https://v6p9d9t4.ssl.hwcdn.net 'self'; child-src https://itch.io https://*.itch.io https://*.itch.zone https://v6p9d9t4.ssl.hwcdn.net 'self';"
    Cross-Origin-Embedder-Policy = "credentialless"